kotlin.code.style=official
org.gradle.jvmargs=-Xmx3G
org.gradle.daemon=false
org.gradle.debug=false

parchment_minecraft_version=1.21.1
parchment_mappings_version=2024.11.17

minecraft_version=1.21.1
minecraft_version_range=[1.21.1,1.22)

neo_version=21.1.233
neo_version_range=[21.1.0,)
loader_version_range=[5.9,)

mapping_channel=official
mapping_version=1.21

mod_id=critterworks
mod_name=Critterworks
mod_license=MIT
mod_version=1.1.0
mod_group_id=dev.aaronhowser.mods
mod_authors=aaronhowser1
mod_credits=LatvianModder - Art and design\\nJuiceyBeans - Art
mod_description=Carts for your favorite critters.

kff_version_range=[5.12.0,6.0.0)
kff_version=5.12.0

aaron_lib_version_range=[1.17,)
aaron_lib_version=1.20.0-build.23

geckolib_version_range=[4.9.2,5)
geckolib_version=4.9.2

jei_version=19.27.0.340

curseforge_id=
modrinth_id=